"""create TTADATTENDANCE table

Revision ID: 9b57d84ef539
Revises: f21140de6daa
Create Date: 2026-09-01 10:32:10.197774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b57d84ef539'
down_revision: Union[str, Sequence[str], None] = 'f21140de6daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TTADATTENDANCE',
    sa.Column('attend_id', sa.String(length=150), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('shiftstarttime', sa.DateTime(), nullable=True),
    sa.Column('shiftendtime', sa.DateTime(), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('actual_in', sa.Integer(), nullable=True),
    sa.Column('actual_out', sa.Integer(), nullable=True),
    sa.Column('actualworkmnt', sa.Integer(), nullable=True),
    sa.Column('daytype', sa.String(length=5), nullable=False),
    sa.Column('attend_code', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.String(length=5000), nullable=True),
    sa.Column('total_ot', sa.Float(), nullable=True),
    sa.Column('total_otindex', sa.Float(), nullable=True),
    sa.Column('ip_starttime', sa.String(length=20), nullable=True),
    sa.Column('ip_endtime', sa.String(length=20), nullable=True),
    sa.Column('photo_start', sa.String(length=255), nullable=True),
    sa.Column('photo_end', sa.String(length=255), nullable=True),
    sa.Column('geoloc_start', sa.String(length=255), nullable=True),
    sa.Column('geoloc_end', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('attend_id')
    )
    op.create_index(op.f('ix_TTADATTENDANCE_emp_id'), 'TTADATTENDANCE', ['emp_id'], unique=False)
    op.create_index(op.f('ix_TTADATTENDANCE_shiftendtime'), 'TTADATTENDANCE', ['shiftendtime'], unique=False)
    op.create_index(op.f('ix_TTADATTENDANCE_shiftstarttime'), 'TTADATTENDANCE', ['shiftstarttime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TTADATTENDANCE_shiftstarttime'), table_name='TTADATTENDANCE')
    op.drop_index(op.f('ix_TTADATTENDANCE_shiftendtime'), table_name='TTADATTENDANCE')
    op.drop_index(op.f('ix_TTADATTENDANCE_emp_id'), table_name='TTADATTENDANCE')
    op.drop_table('TTADATTENDANCE')
    # ### end Alembic commands ###
